import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      label: "About",
      id: "about",
    },
    {
      type: "category",
      label: "Info",
      items: ["info/device-info", "info/fix-softbricks", "info/disassembling", "info/exploits"],
    },
    {
      type: "category",
      label: "Modes",
      items: ["modes/fastboot", "modes/metamode", "modes/preloader", "modes/pcs"],
    },
    {
      type: "category",
      label: "Development",
      items: [
        "dev/bootloader",
        "dev/testpoints",
        "dev/partitions",
        "dev/tools",
      ],
    },
    {
      type: "category",
      label: "Modding",
      items: [
        "modding/custom-bootloader-chikichou",
        "modding/custom-bootloader-chouchou",
        "modding/custom-bootloader-kaeru",
        "modding/custom-recovery-twrp",
        "modding/custom-recovery-ofrp",
        "modding/custom-recovery-pbrp",
        "modding/root",
        "modding/custom-logo",
        "modding/gsi",
        "modding/custom-roms",
        "modding/gcam",
      ],
    },
    {
      type: "category",
      label: "GSI Roms and Custom Roms",
      items: ["gsi_roms/info", "gsi_roms/rating"],
    }
  ],
};

export default sidebars;
